data:
  root: "./dataset/"
  train_dir: "train"
  test_dir: "test"
  raw_dir: "Imgs"
  mask_dir: "GT"
  image_size: 384
  extensions: [".png", ".jpg", ".jpeg", ".bmp", ".tiff"]

model:
  num_res: 8
  base_channel: 64
  embed_dim: 128
  

training:
  model_dir: "./outputs_COD/"
  epochs: 100

  optimizer:
    name: "AdamW"
    lr: 0.0003
    weight_decay: 0.0001
    betas: [0.9, 0.999]

  scheduler:
    name: "CosineAnnealingLR"
    T_max: 100
    eta_min: 0.00001